### ISSUE TITLE
just the basics please

### ISSUE THREAD

**Issue by AndreLeifert** [NatLabs/http-parser.mo#4]
first step _mops add https://github.com/NatLabs/http-parser.mo#v0.1.1_ adds to mops.toml:
_"http-parser.mo" = "https://github.com/NatLabs/http-parser.mo#v0.1.1@9731276abc46b553c435ef70a30ea43716cd0229"_

That makes the second step impossible to work: 
_import HttpParser "mo:HttpParser";_

**Comment by tomijaga** [comment]
Hey @AndreLeifert, 
You can change the name in the mops.toml file from `"http-parser.mo"` to `"HttpParser"`
or change the import to `import HttpParser "mo:http-parser.mo"`

**Comment by AndreLeifert** [comment]
Hi, Tomi.

True. I can. But neither of the proposed changes makes your readme less
misleading.

Kind regards,

André

**Comment by tomijaga** [comment]
Thanks for the feedback.
It's been a while since I last worked on this project and the ecosystem has developed a lot since then.
I'll update the readme to reflect the correct import statement
